# Generated by Django 4.2 on 2023-08-31 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("user", "user"), ("admin", "admin")],
                default="user",
                max_length=5,
                verbose_name="Роль пользователя",
            ),
        ),
    ]
